import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { adminApi, AdminApiError, type AdminRole, type AdminUser, type CreateUserInput, type FieldErrors, type Page } from './adminApi'
import { useAuth } from '../auth/Auth'
import { AdminState, PageHeading } from './AdminOverviewPage'

const emptyForm: CreateUserInput = { username: '', firstName: '', lastName: '', role: 'User', password: '', passwordConfirmation: '' }

export function AdminUsersPage() {
  const { request, user: currentUser } = useAuth(); const [page, setPage] = useState(1); const [searchDraft, setSearchDraft] = useState(''); const [search, setSearch] = useState('')
  const [role, setRole] = useState<'' | AdminRole>(''); const [active, setActive] = useState<'' | 'true' | 'false'>(''); const [data, setData] = useState<Page<AdminUser> | null>(null)
  const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); const [reload, setReload] = useState(0); const [notice, setNotice] = useState('')
  const [form, setForm] = useState<CreateUserInput>(emptyForm); const [formErrors, setFormErrors] = useState<FieldErrors>({}); const [createError, setCreateError] = useState(''); const [creating, setCreating] = useState(false)
  const [statusTarget, setStatusTarget] = useState<AdminUser | null>(null); const [passwordTarget, setPasswordTarget] = useState<AdminUser | null>(null); const triggerRef = useRef<HTMLButtonElement | null>(null)

  useEffect(() => { const controller = new AbortController(); void (async () => { await Promise.resolve(); setState('loading'); try { setData(await adminApi.users(request, { page, pageSize: 20, search, role, isActive: active }, controller.signal)); setState('ready') } catch (error) { if ((error as Error).name !== 'AbortError') setState('error') } })(); return () => controller.abort() }, [request, page, search, role, active, reload])
  function applyFilters(event: FormEvent) { event.preventDefault(); setPage(1); setSearch(searchDraft.trim()) }
  function changeRole(value: '' | AdminRole) { setRole(value); setPage(1) }
  function changeActive(value: '' | 'true' | 'false') { setActive(value); setPage(1) }
  function updateForm<K extends keyof CreateUserInput>(key: K, value: CreateUserInput[K]) { setForm(current => ({ ...current, [key]: value })); setFormErrors(current => ({ ...current, [key]: [] })) }
  async function createUser(event: FormEvent) {
    event.preventDefault(); const local: FieldErrors = {}
    for (const key of ['username', 'firstName', 'lastName', 'password', 'passwordConfirmation'] as const) if (!form[key]) local[key] = ['Bu alan zorunludur.']
    if (form.password && form.password !== form.passwordConfirmation) local.passwordConfirmation = ['Şifreler eşleşmiyor.']
    if (Object.keys(local).length) { setFormErrors(local); setCreateError('Lütfen işaretlenen alanları düzeltin.'); focusFirst(local); return }
    setCreating(true); setCreateError(''); setFormErrors({})
    try { await adminApi.createUser(request, { ...form, username: form.username.trim(), firstName: form.firstName.trim(), lastName: form.lastName.trim() }); setForm(emptyForm); setNotice(`${form.username.trim()} kullanıcısı oluşturuldu.`); setPage(1); setReload(value => value + 1) }
    catch (error) { const apiError = error as AdminApiError; setFormErrors(apiError.fieldErrors); setCreateError(apiError.message); focusFirst(apiError.fieldErrors) }
    finally { setCreating(false) }
  }
  function openStatus(target: AdminUser, trigger: HTMLButtonElement) { triggerRef.current = trigger; setStatusTarget(target) }
  function openPassword(target: AdminUser, trigger: HTMLButtonElement) { triggerRef.current = trigger; setPasswordTarget(target) }
  function closeDialog() { setStatusTarget(null); setPasswordTarget(null); queueMicrotask(() => triggerRef.current?.focus()) }
  async function confirmStatus() { if (!statusTarget) return; await adminApi.setStatus(request, statusTarget.id, !statusTarget.isActive); setNotice(`${statusTarget.username} ${statusTarget.isActive ? 'pasife alındı' : 'aktif edildi'}.`); closeDialog(); setReload(value => value + 1) }
  const pages = data ? Math.max(1, Math.ceil(data.total / data.pageSize)) : 1
  return <section className="admin-page" aria-labelledby="admin-users-title">
    <PageHeading kicker="Yönetim" title="Kullanıcılar" id="admin-users-title" text="Hesap oluşturun, aktiflik durumunu yönetin ve güvenli parola sıfırlaması yapın." />
    {notice && <p className="success-message" role="status">{notice}</p>}
    <section className="admin-panel" aria-labelledby="create-user-title"><h2 id="create-user-title">Yeni kullanıcı</h2>{createError && <p className="error" role="alert">{createError}</p>}
      <form className="admin-form-grid" onSubmit={createUser} noValidate>
        <AdminField label="Kullanıcı adı" name="username" value={form.username} onChange={value => updateForm('username', value)} errors={formErrors.username} autoComplete="off" />
        <AdminField label="Ad" name="firstName" value={form.firstName} onChange={value => updateForm('firstName', value)} errors={formErrors.firstName} autoComplete="off" />
        <AdminField label="Soyad" name="lastName" value={form.lastName} onChange={value => updateForm('lastName', value)} errors={formErrors.lastName} autoComplete="off" />
        <label htmlFor="create-role">Rol<select id="create-role" value={form.role} onChange={event => updateForm('role', event.target.value as AdminRole)}><option value="User">User</option><option value="Admin">Admin</option></select></label>
        <AdminField label="Şifre" name="password" type="password" value={form.password} onChange={value => updateForm('password', value)} errors={formErrors.password} autoComplete="new-password" />
        <AdminField label="Şifre tekrarı" name="passwordConfirmation" type="password" value={form.passwordConfirmation} onChange={value => updateForm('passwordConfirmation', value)} errors={formErrors.passwordConfirmation} autoComplete="new-password" />
        <button disabled={creating}>{creating ? 'Oluşturuluyor…' : 'Kullanıcı oluştur'}</button>
      </form>
    </section>
    <section className="admin-panel" aria-labelledby="user-list-title"><h2 id="user-list-title">Kullanıcı listesi</h2>
      <form className="filter-bar" aria-label="Kullanıcı filtreleri" onSubmit={applyFilters}><label htmlFor="user-search">Kullanıcı ara<input id="user-search" value={searchDraft} onChange={event => setSearchDraft(event.target.value)} /></label><label htmlFor="role-filter">Rol<select id="role-filter" value={role} onChange={event => changeRole(event.target.value as '' | AdminRole)}><option value="">Tümü</option><option value="User">User</option><option value="Admin">Admin</option></select></label><label htmlFor="active-filter">Durum<select id="active-filter" value={active} onChange={event => changeActive(event.target.value as '' | 'true' | 'false')}><option value="">Tümü</option><option value="true">Aktif</option><option value="false">Pasif</option></select></label><button>Ara</button></form>
      {state === 'loading' && <AdminState title="Kullanıcılar yükleniyor…" />}{state === 'error' && <AdminState title="Kullanıcılar yüklenemedi." error onRetry={() => setReload(value => value + 1)} />}
      {state === 'ready' && data?.items.length === 0 && <p className="empty-message">Filtrelere uygun kullanıcı bulunamadı.</p>}
      {state === 'ready' && data && data.items.length > 0 && <div className="responsive-table"><table><caption className="sr-only">Yönetilebilir kullanıcılar</caption><thead><tr><th>Kullanıcı</th><th>Rol</th><th>Durum</th><th>Oluşturulma</th><th>İşlemler</th></tr></thead><tbody>{data.items.map(item => <tr key={item.id}><td data-label="Kullanıcı"><strong>{item.firstName} {item.lastName}</strong><span>@{item.username}</span></td><td data-label="Rol">{item.role}</td><td data-label="Durum"><StatusBadge active={item.isActive} /></td><td data-label="Oluşturulma">{formatDate(item.createdAtUtc)}</td><td data-label="İşlemler" className="row-actions"><button className="secondary-button" disabled={item.username === currentUser?.username && item.isActive} onClick={event => openStatus(item, event.currentTarget)}>{item.isActive ? 'Pasife al' : 'Aktif et'}</button><button className="secondary-button" onClick={event => openPassword(item, event.currentTarget)}>Şifreyi sıfırla</button></td></tr>)}</tbody></table></div>}
      <Pagination page={page} pages={pages} total={data?.total ?? 0} onPage={setPage} />
    </section>
    {statusTarget && <StatusDialog target={statusTarget} onClose={closeDialog} onConfirm={confirmStatus} />}
    {passwordTarget && <PasswordDialog target={passwordTarget} request={request} onClose={closeDialog} onSuccess={() => { setNotice(`${passwordTarget.username} kullanıcısının şifresi güncellendi; refresh oturumları iptal edildi.`); closeDialog() }} />}
  </section>
}

function AdminField({ label, name, value, onChange, errors, type = 'text', autoComplete }: { label: string; name: string; value: string; onChange: (value: string) => void; errors?: string[]; type?: string; autoComplete: string }) { const hasErrors = (errors?.length ?? 0) > 0; return <label htmlFor={`admin-${name}`}>{label}<input id={`admin-${name}`} name={name} type={type} value={value} autoComplete={autoComplete} onChange={event => onChange(event.target.value)} aria-invalid={hasErrors ? 'true' : undefined} aria-describedby={hasErrors ? `admin-${name}-error` : undefined} />{hasErrors && <span id={`admin-${name}-error`} className="field-error">{errors?.join(' ')}</span>}</label> }
function focusFirst(errors: FieldErrors) { const first = ['username', 'firstName', 'lastName', 'password', 'passwordConfirmation'].find(key => errors[key]?.length); if (first) queueMicrotask(() => document.getElementById(`admin-${first}`)?.focus()) }
function StatusBadge({ active }: { active: boolean }) { return <span className={`status-badge ${active ? 'status-success' : 'status-muted'}`}><span aria-hidden="true">{active ? '●' : '○'}</span>{active ? 'Aktif' : 'Pasif'}</span> }
export function Pagination({ page, pages, total, onPage }: { page: number; pages: number; total: number; onPage: (page: number) => void }) { return <nav className="pagination" aria-label="Sayfalama"><button className="secondary-button" disabled={page <= 1} onClick={() => onPage(page - 1)}>Önceki</button><span>Sayfa {page} / {pages} · {total} kayıt</span><button className="secondary-button" disabled={page >= pages} onClick={() => onPage(page + 1)}>Sonraki</button></nav> }

function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { const heading = useRef<HTMLHeadingElement>(null); useEffect(() => { heading.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; document.addEventListener('keydown', escape); return () => document.removeEventListener('keydown', escape) }, [onClose]); return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><h2 id="modal-title" ref={heading} tabIndex={-1}>{title}</h2>{children}</section></div> }
function StatusDialog({ target, onClose, onConfirm }: { target: AdminUser; onClose: () => void; onConfirm: () => Promise<void> }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function confirm() { setBusy(true); try { await onConfirm() } catch (reason) { setError((reason as AdminApiError).message) } finally { setBusy(false) } } return <Modal title={`${target.isActive ? 'Pasife al' : 'Aktif et'}: ${target.username}`} onClose={onClose}><p>Bu kullanıcıyı {target.isActive ? 'pasife almak' : 'aktif etmek'} istediğinizi onaylayın.</p>{target.isActive && <p>Pasife alma işlemi kullanıcının refresh oturumlarını iptal eder.</p>}{error && <p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Vazgeç</button><button className={target.isActive ? 'danger-button' : ''} disabled={busy} onClick={() => void confirm()}>{busy ? 'Uygulanıyor…' : 'Onayla'}</button></div></Modal> }
function PasswordDialog({ target, request, onClose, onSuccess }: { target: AdminUser; request: ReturnType<typeof useAuth>['request']; onClose: () => void; onSuccess: () => void }) { const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); if (!password || password !== confirmation) { setError(password ? 'Şifreler eşleşmiyor.' : 'Şifre zorunludur.'); return } setBusy(true); try { await adminApi.resetPassword(request, target.id, password, confirmation); setPassword(''); setConfirmation(''); onSuccess() } catch (reason) { setError((reason as AdminApiError).message) } finally { setBusy(false) } } function cancel() { setPassword(''); setConfirmation(''); onClose() } return <Modal title={`Şifreyi sıfırla: ${target.username}`} onClose={cancel}><p>Mevcut şifre istenmez. Başarılı işlem tüm refresh oturumlarını iptal eder; mevcut access token en fazla normal 15 dakikalık ömrünün sonuna kadar kullanılabilir.</p><form onSubmit={submit}><label htmlFor="reset-password">Yeni şifre<input id="reset-password" type="password" autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} /></label><label htmlFor="reset-confirmation">Yeni şifre tekrarı<input id="reset-confirmation" type="password" autoComplete="new-password" value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label>{error && <p className="error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={cancel}>Vazgeç</button><button disabled={busy}>{busy ? 'Güncelleniyor…' : 'Şifreyi güncelle'}</button></div></form></Modal> }
function formatDate(value: string) { return new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
