import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { deriveSummaryTitle } from './summaryTitles'

const user = { username: 'member', firstName: 'Test', lastName: 'User', role: 'User' }
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
const sourceText = 'Dijital dönüşüm işletmelerin süreçlerini geliştirir.\nİkinci kaynak satırı.'
const fullSummary = `Dijital dönüşüm süreçleri hızlandırır. ${'Ayrıntılı içerik '.repeat(14)}SON-İŞARET`
const recent = [{ id: 'summary-1', summary: fullSummary, language: 'Turkish', createdAtUtc: '2026-08-02T10:00:00Z', expiresAtUtc: '2026-09-01T10:00:00Z' }]
const detail = { ...recent[0], inputText: sourceText, promptVersion: 'summary-v1' }
function renderAuthenticated(items: unknown[] = recent, path = '/app') { const fetchMock = vi.fn((url: RequestInfo | URL, init?: RequestInit) => { const value = String(url); if (value.endsWith('/api/auth/refresh')) return json({ accessToken: 'opaque', user }); if (value.endsWith('/api/summaries/recent')) return json(items); if (value.endsWith('/api/summaries/summary-1/feedback') && init?.method === 'PUT') { const body = JSON.parse(String(init.body)) as { value: string }; return json({ value: body.value, updatedAtUtc: '2026-08-03T10:00:00Z' }) } if (value.endsWith('/api/summaries/created/feedback') && init?.method === 'PUT') { const body = JSON.parse(String(init.body)) as { value: string }; return json({ value: body.value, updatedAtUtc: '2026-08-03T10:00:00Z' }) } if (value.endsWith('/api/summaries/summary-1')) return json({ ...detail, feedback: (items[0] as { feedback?: unknown } | undefined)?.feedback ?? null }); if (value.endsWith('/api/auth/logout')) return Promise.resolve(new Response(null, { status: 204 })); if (value.endsWith('/api/summaries') && init?.method === 'POST') return json({ id: 'created', summary: 'Dijital dönüşüm için güvenli özet.', language: 'Turkish', createdAtUtc: '2026-08-02T11:00:00Z', expiresAtUtc: '2026-09-01T11:00:00Z', feedback: null }); return json({}, 404) }); vi.stubGlobal('fetch', fetchMock); render(<MemoryRouter initialEntries={[path]}><App /></MemoryRouter>); return fetchMock }
afterEach(() => { cleanup(); vi.restoreAllMocks(); localStorage.clear() })

describe('product workspace', () => {
  it('derives localized deterministic titles and fallbacks', () => { expect(deriveSummaryTitle('Dijital dönüşüm kurumları yeniler.', '', 'Turkish')).toBe('Dijital Dönüşüm'); expect(deriveSummaryTitle('Digital transformation improves operations.', '', 'English')).toBe('Digital Transformation'); expect(deriveSummaryTitle('', 'tek', 'Turkish')).toBe('Yeni Özet'); expect(deriveSummaryTitle('', '', 'English')).toBe('New Summary') })

  it('opens and closes the sidebar without authentication effects', async () => { const fetchMock = renderAuthenticated(); const toggle = await screen.findByRole('button', { name: 'Kenar çubuğunu kapat' }); expect(toggle).toHaveAttribute('aria-expanded', 'true'); fireEvent.click(toggle); expect(screen.getByRole('button', { name: 'Kenar çubuğunu aç' })).toHaveAttribute('aria-expanded', 'false'); fireEvent.click(screen.getByRole('button', { name: 'Kenar çubuğunu aç' })); expect(screen.getByRole('button', { name: 'Kenar çubuğunu kapat' })).toBeVisible(); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/auth/logout'))).toBe(false) })

  it('closes the mobile drawer with Escape and restores toggle focus', async () => { vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: true, addEventListener: vi.fn(), removeEventListener: vi.fn() }))); renderAuthenticated(); const open = await screen.findByRole('button', { name: 'Kenar çubuğunu aç' }); fireEvent.click(open); expect(screen.getAllByRole('button', { name: 'Kenar çubuğunu kapat' }).length).toBeGreaterThan(1); fireEvent.keyDown(document, { key: 'Escape' }); expect(screen.getByRole('button', { name: 'Kenar çubuğunu aç' })).toHaveFocus() })

  it('keeps cards compact and loads source plus summary detail on demand', async () => { const fetchMock = renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(screen.queryByText(/İkinci kaynak satırı/)).not.toBeInTheDocument(); expect(screen.queryByText(/SON-İŞARET/)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Tam özeti aç' })); expect(await screen.findByRole('heading', { name: 'Kaynak metin' })).toBeVisible(); expect(screen.getByRole('heading', { name: 'Oluşturulan özet' })).toBeVisible(); expect(screen.getByText(/İkinci kaynak satırı/)).toBeVisible(); expect(screen.getByText(/SON-İŞARET/)).toBeVisible(); expect(screen.queryByText(/Şablon sürümü/)).not.toBeInTheDocument(); expect(fetchMock.mock.calls.filter(call => String(call[0]).endsWith('/api/summaries/summary-1'))).toHaveLength(1); expect(localStorage.getItem('ifs-aiweb:pinned-summary-ids')).toBeNull(); fireEvent.click(screen.getByRole('button', { name: '← Geri dön' })); expect(await screen.findByRole('heading', { name: 'Son özetleriniz' })).toBeVisible(); expect(screen.getByRole('button', { name: 'Tam özeti aç' })).toHaveFocus() })

  it('shows independent detail loading and a safe retryable missing-or-expired error', async () => { const fetchMock = renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); let resolve!: (value: Response) => void; fetchMock.mockImplementationOnce(() => new Promise<Response>(done => { resolve = done })); fireEvent.click(screen.getByRole('button', { name: 'Tam özeti aç' })); expect(await screen.findByRole('status')).toHaveTextContent('Özet ayrıntıları yükleniyor'); resolve(await json({}, 404)); expect(await screen.findByRole('alert')).toHaveTextContent('Bu özet bulunamadı veya saklama süresi dolmuş olabilir.'); expect(screen.queryByText(sourceText)).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Yeniden dene' })).toBeVisible() })

  it('submits accessible feedback from historical detail and reflects it textually in history', async () => {
    const fetchMock = renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(screen.queryByRole('button', { name: 'Faydalı' })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Tam özeti aç' }));
    const useful = await screen.findByRole('button', { name: 'Faydalı' }); expect(useful).toHaveAttribute('aria-pressed', 'false'); fireEvent.click(useful);
    await waitFor(() => expect(useful).toHaveAttribute('aria-pressed', 'true')); expect(screen.getByText('Faydalı olarak değerlendirildi')).toBeVisible();
    const call = fetchMock.mock.calls.find(([url, init]) => String(url).endsWith('/api/summaries/summary-1/feedback') && (init as RequestInit)?.method === 'PUT'); expect(JSON.parse(String((call![1] as RequestInit).body))).toEqual({ value: 'Useful' });
    fireEvent.click(screen.getByRole('button', { name: '← Geri dön' })); expect(await screen.findByText('Faydalı olarak değerlendirildi')).toBeVisible(); expect(screen.queryByRole('button', { name: 'Faydalı' })).not.toBeInTheDocument();
  })

  it('restores server-confirmed feedback in both recent history and detail', async () => {
    renderAuthenticated([{ ...recent[0], feedback: 'NotUseful' }]); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(await screen.findByText('Faydalı değil olarak değerlendirildi')).toBeVisible(); expect(screen.queryByRole('button', { name: 'Faydalı değil' })).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Tam özeti aç' })); expect(await screen.findByRole('button', { name: 'Faydalı değil' })).toHaveAttribute('aria-pressed', 'true'); expect(screen.getByRole('button', { name: 'Faydalı' })).toHaveAttribute('aria-pressed', 'false');
  })

  it('supports feedback on a new result, prevents duplicate pending requests and retains confirmed state after failure', async () => {
    const fetchMock = renderAuthenticated(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'Dijital dönüşüm kaynak metni' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' }));
    const useful = await screen.findByRole('button', { name: 'Faydalı' }); fireEvent.click(useful); await waitFor(() => expect(useful).toHaveAttribute('aria-pressed', 'true'));
    let reject!: (value: Response) => void; fetchMock.mockImplementationOnce(() => new Promise<Response>(done => { reject = done })); const notUseful = screen.getByRole('button', { name: 'Faydalı değil' }); fireEvent.click(notUseful); expect(useful).toBeDisabled(); expect(notUseful).toBeDisabled(); fireEvent.click(notUseful);
    expect(fetchMock.mock.calls.filter(([url, init]) => String(url).endsWith('/feedback') && (init as RequestInit)?.method === 'PUT')).toHaveLength(2); reject(await json({}, 500));
    expect(await screen.findByRole('alert')).toHaveTextContent('Değerlendirmeniz kaydedilemedi.'); expect(useful).toHaveAttribute('aria-pressed', 'true'); expect(notUseful).toHaveAttribute('aria-pressed', 'false');
  })

  it('renders retained source and summary strictly as plain text', async () => { const unsafe = '<img src=x onerror=alert(1)>'; renderAuthenticated([{ ...recent[0], summary: unsafe }]); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); vi.mocked(fetch).mockImplementationOnce(() => json({ ...detail, inputText: unsafe, summary: unsafe })); fireEvent.click(screen.getByRole('button', { name: 'Tam özeti aç' })); expect((await screen.findAllByText(unsafe)).length).toBeGreaterThanOrEqual(2); expect(document.querySelector('img')).toBeNull() })

  it('new summary clears only working state and preserves history', async () => { const fetchMock = renderAuthenticated(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'Dijital dönüşüm kaynak metni' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByText('Dijital dönüşüm için güvenli özet.')).toBeVisible(); fireEvent.click(screen.getAllByRole('button', { name: 'Yeni özet' })[1]); expect(await screen.findByLabelText('Kaynak metin')).toHaveValue(''); expect(screen.getByRole('button', { name: 'Dijital Dönüşüm' })).toBeVisible(); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/auth/logout'))).toBe(false) })

  it('stores only pinned identifiers and supports unpinning', async () => { renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); const pin = screen.getByRole('button', { name: 'Özeti sabitle' }); fireEvent.click(pin); expect(localStorage.getItem('ifs-aiweb:pinned-summary-ids')).toBe('["summary-1"]'); expect(screen.getByRole('button', { name: 'Sabitlemeyi kaldır' })).toHaveAttribute('aria-pressed', 'true'); fireEvent.click(screen.getByRole('button', { name: 'Sabitlemeyi kaldır' })); expect(localStorage.getItem('ifs-aiweb:pinned-summary-ids')).toBe('[]') })

  it('restores a valid session on a public auth route and does not persist tokens', async () => { const storageSpy = vi.spyOn(Storage.prototype, 'setItem'); renderAuthenticated([], '/login'); expect(await screen.findByLabelText('Kaynak metin')).toBeVisible(); expect(screen.queryByRole('heading', { name: 'Giriş yap' })).not.toBeInTheDocument(); expect(storageSpy).not.toHaveBeenCalledWith(expect.any(String), expect.stringContaining('opaque')) })

  it('logs out only after the explicit account action', async () => { const fetchMock = renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/auth/logout'))).toBe(false); fireEvent.click(screen.getByRole('button', { name: 'Çıkış yap' })); await waitFor(() => expect(fetchMock.mock.calls.filter(call => String(call[0]).endsWith('/api/auth/logout'))).toHaveLength(1)); expect(await screen.findByRole('heading', { name: 'Giriş yap' })).toBeVisible() })
})
