import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { deriveSummaryTitle } from './summaryTitles'

const user = { username: 'member', firstName: 'Test', lastName: 'User', role: 'User' }
const json = (body: unknown, status = 200) => Promise.resolve(new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
const recent = [{ id: 'summary-1', inputText: 'Dijital dönüşüm işletmelerin süreçlerini geliştirir.', summary: `Dijital dönüşüm süreçleri hızlandırır. ${'Ayrıntılı içerik '.repeat(14)}SON-İŞARET`, language: 'Turkish', createdAtUtc: '2026-08-02T10:00:00Z', expiresAtUtc: '2026-09-01T10:00:00Z' }]
function renderAuthenticated(items: unknown[] = recent, path = '/app') { const fetchMock = vi.fn((url: RequestInfo | URL, init?: RequestInit) => { const value = String(url); if (value.endsWith('/api/auth/refresh')) return json({ accessToken: 'opaque', user }); if (value.endsWith('/api/summaries/recent')) return json(items); if (value.endsWith('/api/auth/logout')) return Promise.resolve(new Response(null, { status: 204 })); if (value.endsWith('/api/summaries') && init?.method === 'POST') return json({ id: 'created', summary: 'Dijital dönüşüm için güvenli özet.', language: 'Turkish', createdAtUtc: '2026-08-02T11:00:00Z', expiresAtUtc: '2026-09-01T11:00:00Z' }); return json({}, 404) }); vi.stubGlobal('fetch', fetchMock); render(<MemoryRouter initialEntries={[path]}><App /></MemoryRouter>); return fetchMock }
afterEach(() => { cleanup(); vi.restoreAllMocks(); localStorage.clear() })

describe('product workspace', () => {
  it('derives localized deterministic titles and fallbacks', () => { expect(deriveSummaryTitle('Dijital dönüşüm kurumları yeniler.', '', 'Turkish')).toBe('Dijital Dönüşüm Özeti'); expect(deriveSummaryTitle('Digital transformation improves operations.', '', 'English')).toBe('Digital Transformation Summary'); expect(deriveSummaryTitle('', 'tek', 'Turkish')).toBe('Yeni Özet'); expect(deriveSummaryTitle('', '', 'English')).toBe('New Summary') })

  it('opens and closes the sidebar without authentication effects', async () => { const fetchMock = renderAuthenticated(); const toggle = await screen.findByRole('button', { name: 'Kenar çubuğunu kapat' }); expect(toggle).toHaveAttribute('aria-expanded', 'true'); fireEvent.click(toggle); expect(screen.getByRole('button', { name: 'Kenar çubuğunu aç' })).toHaveAttribute('aria-expanded', 'false'); fireEvent.click(screen.getByRole('button', { name: 'Kenar çubuğunu aç' })); expect(screen.getByRole('button', { name: 'Kenar çubuğunu kapat' })).toBeVisible(); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/auth/logout'))).toBe(false) })

  it('closes the mobile drawer with Escape and restores toggle focus', async () => { vi.stubGlobal('matchMedia', vi.fn(() => ({ matches: true, addEventListener: vi.fn(), removeEventListener: vi.fn() }))); renderAuthenticated(); const open = await screen.findByRole('button', { name: 'Kenar çubuğunu aç' }); fireEvent.click(open); expect(screen.getAllByRole('button', { name: 'Kenar çubuğunu kapat' }).length).toBeGreaterThan(1); fireEvent.keyDown(document, { key: 'Escape' }); expect(screen.getByRole('button', { name: 'Kenar çubuğunu aç' })).toHaveFocus() })

  it('keeps cards compact and opens the complete summary on demand', async () => { renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(screen.queryByText(/SON-İŞARET/)).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Tam özeti aç' })); expect(await screen.findByText(/SON-İŞARET/)).toBeVisible(); expect(screen.getByRole('heading', { name: 'Dijital Dönüşüm Özeti' })).toBeVisible() })

  it('new summary clears only working state and preserves history', async () => { const fetchMock = renderAuthenticated(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'Dijital dönüşüm kaynak metni' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByText('Dijital dönüşüm için güvenli özet.')).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: 'Yeni özet' })); expect(await screen.findByLabelText('Kaynak metin')).toHaveValue(''); expect(screen.getByRole('button', { name: 'Dijital Dönüşüm Özeti' })).toBeVisible(); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/auth/logout'))).toBe(false) })

  it('stores only pinned identifiers and supports unpinning', async () => { renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); const pin = screen.getByRole('button', { name: 'Özeti sabitle' }); fireEvent.click(pin); expect(localStorage.getItem('ifs-aiweb:pinned-summary-ids')).toBe('["summary-1"]'); expect(screen.getByRole('button', { name: 'Sabitlemeyi kaldır' })).toHaveAttribute('aria-pressed', 'true'); fireEvent.click(screen.getByRole('button', { name: 'Sabitlemeyi kaldır' })); expect(localStorage.getItem('ifs-aiweb:pinned-summary-ids')).toBe('[]') })

  it('restores a valid session on a public auth route and does not persist tokens', async () => { const storageSpy = vi.spyOn(Storage.prototype, 'setItem'); renderAuthenticated([], '/login'); expect(await screen.findByLabelText('Kaynak metin')).toBeVisible(); expect(screen.queryByRole('heading', { name: 'Giriş yap' })).not.toBeInTheDocument(); expect(storageSpy).not.toHaveBeenCalledWith(expect.any(String), expect.stringContaining('opaque')) })

  it('logs out only after the explicit account action', async () => { const fetchMock = renderAuthenticated(); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/auth/logout'))).toBe(false); fireEvent.click(screen.getByRole('button', { name: 'Çıkış yap' })); await waitFor(() => expect(fetchMock.mock.calls.filter(call => String(call[0]).endsWith('/api/auth/logout'))).toHaveLength(1)); expect(await screen.findByRole('heading', { name: 'Giriş yap' })).toBeVisible() })
})
