import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'

const user = { username: 'member', firstName: 'Test', lastName: 'User', role: 'User' }
const response = (body: unknown, status = 200) => Promise.resolve(new Response(status === 204 ? null : JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
function renderApp(recent: unknown[] = []) { const fetchMock = vi.fn().mockImplementationOnce(() => response({ accessToken: 'opaque', user })).mockImplementationOnce(() => response(recent)); vi.stubGlobal('fetch', fetchMock); render(<MemoryRouter initialEntries={['/app']}><App /></MemoryRouter>); return fetchMock }
afterEach(() => { cleanup(); vi.restoreAllMocks() })

describe('summarization experience', () => {
  it('renders authenticated controls, empty history and retention disclosure', async () => { renderApp(); expect(await screen.findByLabelText('Kaynak metin')).toBeVisible(); expect(screen.getByText(/30 gün saklanır/)).toBeVisible(); expect(await screen.findByText('Henüz özet yok.')).toBeVisible(); expect(screen.getByRole('button', { name: 'Özet oluştur' })).toBeDisabled() })
  it('renders all seven compact recent summaries returned by the API', async () => { const items = Array.from({ length: 7 }, (_, index) => ({ id: `recent-${index}`, summary: `Güvenli özet ${index + 1}`, language: 'Turkish', createdAtUtc: new Date(2026, 7, 3, 12, index).toISOString(), expiresAtUtc: new Date(2026, 8, 2, 12, index).toISOString() })); renderApp(items); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(await screen.findByText('API en yeni yedi uygun başarılı özetin kompakt listesini sunuyor.')).toBeVisible(); expect(screen.getAllByRole('button', { name: 'Tam özeti aç' })).toHaveLength(7); expect(screen.queryByText(/Kaynak metin:/)).not.toBeInTheDocument() })
  it('updates count and blocks over-limit input', async () => { renderApp(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'abc' } }); expect(screen.getByText('3 / 12.000')).toBeVisible(); fireEvent.change(area, { target: { value: 'x'.repeat(12001) } }); expect(screen.getByRole('button', { name: 'Özet oluştur' })).toBeDisabled() })
  it.each([['12345', 'Metin en az bir harf içermelidir.'], ['!?.,---', 'Metin en az bir harf içermelidir.'], ['aaaaaaaa', 'Metin aynı karakterin uzun tekrarından oluşamaz.']])('blocks structurally invalid input without a request: %s', async (value, message) => { const fetchMock = renderApp(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value } }); expect(screen.getByText(message)).toBeVisible(); expect(screen.getByRole('button', { name: 'Özet oluştur' })).toBeDisabled(); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/summaries') && (call[1] as RequestInit)?.method === 'POST')).toBe(false) })
  it.each(['Merhaba', 'erfdv'])('blocks one-word input without a request: %s', async value => { const fetchMock = renderApp(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value } }); expect(screen.getByText('Özetlemek için en az iki kelimeden oluşan bir metin girin.')).toBeVisible(); expect(screen.getByRole('button', { name: 'Özet oluştur' })).toBeDisabled(); expect(fetchMock.mock.calls.some(call => String(call[0]).endsWith('/api/summaries') && (call[1] as RequestInit)?.method === 'POST')).toBe(false) })
  it.each([['Türkçe', 'Turkish', 'Toplantı ertelendi.'], ['İngilizce', 'English', 'Meeting postponed.']])('submits valid short %s content', async (label, value, source) => { const fetchMock = renderApp(); fetchMock.mockImplementationOnce(() => response({ id: '1', summary: 'Güvenli özet', language: value, createdAtUtc: new Date().toISOString(), expiresAtUtc: new Date().toISOString() })).mockImplementationOnce(() => response([])); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: source } }); fireEvent.click(screen.getByLabelText(label)); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByText('Güvenli özet')).toBeVisible(); const post = fetchMock.mock.calls.find(call => String(call[0]).endsWith('/api/summaries') && (call[1] as RequestInit)?.method === 'POST'); expect(JSON.parse(String((post![1] as RequestInit).body)).language).toBe(value) })
  it('prevents duplicate submission while loading', async () => { const fetchMock = renderApp(); let resolve!: (value: Response) => void; fetchMock.mockImplementationOnce(() => new Promise<Response>(done => { resolve = done })); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'valid source' } }); const button = screen.getByRole('button', { name: 'Özet oluştur' }); fireEvent.click(button); expect(await screen.findByRole('button', { name: 'Özetleniyor…' })).toBeDisabled(); fireEvent.click(button); expect(fetchMock.mock.calls.filter(call => String(call[0]).endsWith('/api/summaries') && (call[1] as RequestInit)?.method === 'POST')).toHaveLength(1); resolve(await response({ id: '1', summary: 'done', language: 'Turkish', createdAtUtc: '', expiresAtUtc: '' })) })
  it('shows safe errors and keeps content usable', async () => { const fetchMock = renderApp(); fetchMock.mockImplementationOnce(() => response({ detail: 'raw provider detail' }, 502)); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'private input' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByRole('alert')).toHaveTextContent('Özet şu anda oluşturulamadı'); expect(area).toHaveValue('private input'); expect(screen.queryByText(/raw provider detail/)).not.toBeInTheDocument() })
  it.each([[400, { errors: { text: ['Metin en az bir harf içermelidir.'], unexpected: ['raw unsafe detail'] } }, 'Metin en az bir harf içermelidir.'], [413, { detail: 'raw body' }, 'Gönderilen metin isteği çok büyük.'], [429, { detail: 'raw body' }, 'İstek sınırına ulaştınız.']])('maps HTTP %s safely and preserves input', async (status, body, expected) => { const fetchMock = renderApp(); fetchMock.mockImplementationOnce(() => response(body, status as number)); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'private input' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByRole('alert')).toHaveTextContent(expected as string); expect(area).toHaveValue('private input'); expect(screen.queryByText(/raw unsafe detail|raw body/)).not.toBeInTheDocument() })
  it('handles insufficient content safely without clearing input or adding recent history', async () => { const fetchMock = renderApp(); fetchMock.mockImplementationOnce(() => response({ code: 'insufficient_content', detail: 'raw provider wording' }, 422)); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'random words here' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByRole('alert')).toHaveTextContent('Bu metinde özetlenebilecek yeterli ve anlamlı içerik bulunamadı. Lütfen daha açıklayıcı bir metin girin.'); expect(area).toHaveValue('random words here'); expect(screen.queryByText('raw provider wording')).not.toBeInTheDocument(); expect(await screen.findByText('Henüz özet yok.')).toBeVisible(); expect(fetchMock.mock.calls.filter(call => String(call[0]).endsWith('/api/summaries/recent'))).toHaveLength(1) })
  it('renders provider output as text, not HTML', async () => { renderApp([{ id: '1', summary: '<img src=x onerror=alert(1)>', language: 'English', createdAtUtc: new Date().toISOString(), expiresAtUtc: new Date().toISOString() }]); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(await screen.findByText('<img src=x onerror=alert(1)>')).toBeVisible(); expect(document.querySelector('img')).toBeNull() })
})
