import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'

const user = { username: 'member', firstName: 'Test', lastName: 'User', role: 'User' }
const response = (body: unknown, status = 200) => Promise.resolve(new Response(status === 204 ? null : JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } }))
function renderApp(recent: unknown[] = []) { const fetchMock = vi.fn().mockImplementationOnce(() => response({ accessToken: 'opaque', user })).mockImplementationOnce(() => response(recent)); vi.stubGlobal('fetch', fetchMock); render(<MemoryRouter initialEntries={['/app']}><App /></MemoryRouter>); return fetchMock }
afterEach(() => { cleanup(); vi.restoreAllMocks() })

describe('summarization experience', () => {
  it('renders authenticated controls, empty history and retention disclosure', async () => { renderApp(); expect(await screen.findByLabelText('Kaynak metin')).toBeVisible(); expect(screen.getByText(/30 gün saklanır/)).toBeVisible(); expect(await screen.findByText('Henüz özet yok.')).toBeVisible(); expect(screen.getByRole('button', { name: 'Özet oluştur' })).toBeDisabled() })
  it('updates count and blocks over-limit input', async () => { renderApp(); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'abc' } }); expect(screen.getByText('3 / 12.000')).toBeVisible(); fireEvent.change(area, { target: { value: 'x'.repeat(12001) } }); expect(screen.getByRole('button', { name: 'Özet oluştur' })).toBeDisabled() })
  it.each([['Türkçe', 'Turkish'], ['İngilizce', 'English']])('submits %s selection', async (label, value) => { const fetchMock = renderApp(); fetchMock.mockImplementationOnce(() => response({ id: '1', summary: 'Güvenli özet', language: value, createdAtUtc: new Date().toISOString(), expiresAtUtc: new Date().toISOString() })).mockImplementationOnce(() => response([])); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'valid source' } }); fireEvent.click(screen.getByLabelText(label)); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByText('Güvenli özet')).toBeVisible(); const post = fetchMock.mock.calls.find(call => String(call[0]).endsWith('/api/summaries') && (call[1] as RequestInit)?.method === 'POST'); expect(JSON.parse(String((post![1] as RequestInit).body)).language).toBe(value) })
  it('prevents duplicate submission while loading', async () => { const fetchMock = renderApp(); let resolve!: (value: Response) => void; fetchMock.mockImplementationOnce(() => new Promise<Response>(done => { resolve = done })); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'valid source' } }); const button = screen.getByRole('button', { name: 'Özet oluştur' }); fireEvent.click(button); expect(await screen.findByRole('button', { name: 'Özetleniyor…' })).toBeDisabled(); fireEvent.click(button); expect(fetchMock.mock.calls.filter(call => String(call[0]).endsWith('/api/summaries') && (call[1] as RequestInit)?.method === 'POST')).toHaveLength(1); resolve(await response({ id: '1', summary: 'done', language: 'Turkish', createdAtUtc: '', expiresAtUtc: '' })) })
  it('shows safe errors and keeps content usable', async () => { const fetchMock = renderApp(); fetchMock.mockImplementationOnce(() => response({ detail: 'raw provider detail' }, 502)); const area = await screen.findByLabelText('Kaynak metin'); fireEvent.change(area, { target: { value: 'private input' } }); fireEvent.click(screen.getByRole('button', { name: 'Özet oluştur' })); expect(await screen.findByRole('alert')).toHaveTextContent('Özet şu anda oluşturulamadı'); expect(area).toHaveValue('private input'); expect(screen.queryByText(/raw provider detail/)).not.toBeInTheDocument() })
  it('renders provider output as text, not HTML', async () => { renderApp([{ id: '1', summary: '<img src=x onerror=alert(1)>', language: 'English', createdAtUtc: new Date().toISOString(), expiresAtUtc: new Date().toISOString() }]); fireEvent.click(await screen.findByRole('button', { name: 'Kitaplık' })); expect(await screen.findByText('<img src=x onerror=alert(1)>')).toBeVisible(); expect(document.querySelector('img')).toBeNull() })
})
